---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-help-helper-bot-web
  namespace: default
  labels:
    app: dev-help-helper-bot
    component: web
    layer: application
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: dev-help-helper-bot
      component: web
      layer: application
  template:
    metadata:
      labels:
        app: dev-help-helper-bot
        component: web
        layer: application
      name: dev-help-helper-bot-web
    spec:
      containers:
        - name: dev-help-helper-bot-web
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: production
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: dev-help-helper-bot-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/dev-help-helper-bot:staging
          imagePullPolicy: Always
          ports:
            - name: devhelpbot-http
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: devhelpbot-http
              path: /health/ping
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dev-help-helper-bot-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-help-helper-bot-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-help-helper-bot
    component: web
    layer: application
  name: dev-help-helper-bot-web-internal
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: dev-help-helper-bot
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dev-help-helper-bot
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ cloudflareIpSourceRanges|join(',') }}"
spec:
  ingressClassName: nginx
  rules:
    - host: dev-help-helper-bot-staging.artsy.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: dev-help-helper-bot-web-internal
              servicePort: http
